-- market_banks表初始化
insert into market_banks(version, country, bank_code, bank_name, bank_long_name, status) values
('1', '+62', 'DC_BCA', 'Bank Central Asia (BCA)','Bank Central Asia (BCA)','ACTIVE'),
('1', '+62', 'DC_BNI', 'Bank Negara Indonesia (BNI)','Bank Negara Indonesia (BNI)','ACTIVE'),
('1', '+62', 'DC_BRI', 'Bank Rakyat Indonesia (BRI)','Bank Rakyat Indonesia (BRI)','ACTIVE'),
('1', '+62', 'DC_CIMB', 'Bank CIMB Niaga','Bank CIMB Niaga','ACTIVE'),
('1', '+62', 'DC_DANAMON', 'Bank Danamon','Bank Danamon','ACTIVE'),
('1', '+62', 'DC_MANDIR', 'Bank Mandiri','Bank Mandiri','ACTIVE'),
('1', '+62', 'DC_MEGA', 'Bank Mega','Bank Mega','ACTIVE'),
('1', '+62', 'DC_PANIN', 'Bank Panin','Bank Panin','ACTIVE'),
('1', '+62', 'DC_PERMATA', 'Bank Permata','Bank Permata','ACTIVE'),
('1', '+62', 'DC_BTN', 'Bank Tabungan Negara (BTN)','Bank Tabungan Negara (BTN)','ACTIVE'),
('1', '+62', 'DC_UOB', 'Bank UOB Indonesia','Bank UOB Indonesia','ACTIVE'),
('1', '+62', 'DC_BII', 'Bank Maybank','Bank Maybank','INACTIVE'),
('1', '+62', 'DC_BTPN ', 'BANK BTPN','BANK BTPN','INACTIVE'),
('1', '+62', 'DC_ACEH', 'BPD Aceh','BPD Aceh','INACTIVE'),
('1', '+62', 'DC_ANTAR_DAERAH', 'Bank Antar Daerah','Bank Antar Daerah','INACTIVE'),
('1', '+62', 'DC_ARTHA', 'Bank Artha Graha International','Bank Artha Graha International','INACTIVE'),
('1', '+62', 'DC_BALI', 'BPD Bali','BPD Bali','INACTIVE'),
('1', '+62', 'DC_BANK_JATIM', 'Bank Jatim','Bank Jatim','INACTIVE'),
('1', '+62', 'DC_BCA_SYR', 'Bank Central Asia (BCA) Syariah','Bank Central Asia (BCA) Syariah','INACTIVE'),
('1', '+62', 'DC_BENGKULU', 'BPD Bengkulu','BPD Bengkulu','INACTIVE'),
('1', '+62', 'DC_BJB', 'Bank BJB','Bank BJB','INACTIVE'),
('1', '+62', 'DC_BJB_SYR', 'Bank BJB Syariah','Bank BJB Syariah','INACTIVE'),
('1', '+62', 'DC_BNI_SYR', 'Bank BNI Syariah','Bank BNI Syariah','INACTIVE'),
('1', '+62', 'DC_BRI_SYR', 'Bank Syariah BRI','Bank Syariah BRI','INACTIVE'),
('1', '+62', 'DC_BUKOPIN', 'Bank Bukopin','Bank Bukopin','INACTIVE'),
('1', '+62', 'DC_BUKOPIN_SYR', 'Bank Syariah Bukopin','Bank Syariah Bukopin','INACTIVE'),
('1', '+62', 'DC_BUMI_ARTA', 'Bank Bumi Arta','Bank Bumi Arta','INACTIVE'),
('1', '+62', 'DC_CHINATRUST', 'Bank Chinatrust Indonesia','Bank Chinatrust Indonesia','INACTIVE'),
('1', '+62', 'DC_CITIBANK', 'Citibank','Citibank','INACTIVE'),
('1', '+62', 'DC_COMMONWEALTH', 'Bank Commonwealth','Bank Commonwealth','INACTIVE'),
('1', '+62', 'DC_DBS', 'Bank DBS Indonesia','Bank DBS Indonesia','INACTIVE'),
('1', '+62', 'DC_DEUTSCHE', 'Deutsche Bank','Deutsche Bank','INACTIVE'),
('1', '+62', 'DC_HANA', 'Bank Hana','Bank Hana','INACTIVE'),
('1', '+62', 'DC_HSBC', 'Hongkong and Shanghai Bank Corporation (HSBC)','Hongkong and Shanghai Bank Corporation (HSBC)','INACTIVE'),
('1', '+62', 'DC_ICBC', 'Bank ICBC Indonesia','Bank ICBC Indonesia','INACTIVE'),
('1', '+62', 'DC_JAMBI', 'BPD Jambi','BPD Jambi','INACTIVE'),
('1', '+62', 'DC_JASA_JAKARTA', 'Bank Jasa Jakarta','Bank Jasa Jakarta','INACTIVE'),
('1', '+62', 'DC_JAWA_TENGAH', 'BPD Jawa Tengah','BPD Jawa Tengah','INACTIVE'),
('1', '+62', 'DC_KALIMANTAN_BARAT', 'BPD Kalimantan Barat','BPD Kalimantan Barat','INACTIVE'),
('1', '+62', 'DC_KALIMANTAN_SELATAN', 'BPD Kalimantan Selatan','BPD Kalimantan Selatan','INACTIVE'),
('1', '+62', 'DC_KALIMANTAN_TENGAH', 'BPD Kalimantan Tengah','BPD Kalimantan Tengah','INACTIVE'),
('1', '+62', 'DC_KALIMANTAN_TIMUR', 'BPD Kalimantan Timur','BPD Kalimantan Timur','INACTIVE'),
('1', '+62', 'DC_LAMPUNG', 'BPD Lampung','BPD Lampung','INACTIVE'),
('1', '+62', 'DC_MALUKU', 'BPD Maluku','BPD Maluku','INACTIVE'),
('1', '+62', 'DC_MANDIRI_SYR', 'Bank Syariah Mandiri','Bank Syariah Mandiri','INACTIVE'),
('1', '+62', 'DC_MASPION', 'Bank Maspion Indonesia','Bank Maspion Indonesia','INACTIVE'),
('1', '+62', 'DC_MAYAPADA', 'Bank Mayapada International','Bank Mayapada International','INACTIVE'),
('1', '+62', 'DC_MAYORA', 'Bank Mayora','Bank Mayora','INACTIVE'),
('1', '+62', 'DC_MEGA_SYR', 'Bank Syariah Mega','Bank Syariah Mega','INACTIVE'),
('1', '+62', 'DC_MITSUI', 'Bank Sumitomo Mitsui Indonesia','Bank Sumitomo Mitsui Indonesia','INACTIVE'),
('1', '+62', 'DC_MUAMALAT', 'Bank Muamalat Indonesia','Bank Muamalat Indonesia','INACTIVE'),
('1', '+62', 'DC_MUTIARA', 'Bank Mutiara','Bank Mutiara','INACTIVE'),
('1', '+62', 'DC_NATIONALNOBU', 'Bank Nationalnobu','Bank Nationalnobu','INACTIVE'),
('1', '+62', 'DC_NUSANTARA_PARAHYANGAN', 'Bank Nusantara Parahyangan','Bank Nusantara Parahyangan','INACTIVE'),
('1', '+62', 'DC_NUSA_TENGGARA_BARAT', 'BPD Nusa Tenggara Barat','BPD Nusa Tenggara Barat','INACTIVE'),
('1', '+62', 'DC_NUSA_TENGGARA_TIMUR', 'BPD Nusa Tenggara Timur','BPD Nusa Tenggara Timur','INACTIVE'),
('1', '+62', 'DC_OCBC', 'Bank OCBC NISP','Bank OCBC NISP','INACTIVE'),
('1', '+62', 'DC_PAPUA', 'BPD Papua','BPD Papua','INACTIVE'),
('1', '+62', 'DC_QNB_KESAWAN', 'Bank QNB Kesawan','Bank QNB Kesawan','INACTIVE'),
('1', '+62', 'DC_RABOBANK', 'Bank Rabobank International Indonesia','Bank Rabobank International Indonesia','INACTIVE'),
('1', '+62', 'DC_RBS', 'Royal Bank of Scotland (RBS)','Royal Bank of Scotland (RBS)','INACTIVE'),
('1', '+62', 'DC_RIAU_DAN_KEPRI', 'BPD Riau Dan Kepri','BPD Riau Dan Kepri','INACTIVE'),
('1', '+62', 'DC_SAHABAT_SAMPOERNA', 'Bank Sahabat Sampoerna','Bank Sahabat Sampoerna','INACTIVE'),
('1', '+62', 'DC_SINARMAS', 'Sinarmas','Sinarmas','INACTIVE'),
('1', '+62', 'DC_STANDARD_CHARTERED', 'Standard Charted Bank','Standard Charted Bank','INACTIVE'),
('1', '+62', 'DC_SULAWESI', 'BPD Sulawesi Tengah','BPD Sulawesi Tengah','INACTIVE'),
('1', '+62', 'DC_SULAWESI_TENGGARA', 'BPD Sulawesi Tenggara','BPD Sulawesi Tenggara','INACTIVE'),
('1', '+62', 'DC_SUMATERA_BARAT', 'BPD Sumatera Barat','BPD Sumatera Barat','INACTIVE'),
('1', '+62', 'DC_TABUNGAN_PENSIUNAN_NASIONAL', 'Bank Tabungan Pensiunan Nasional','Bank Tabungan Pensiunan Nasional','INACTIVE'),
('1', '+62', 'DC_TOKYO', 'Bank of Tokyo Mitsubishi UFJ','Bank of Tokyo Mitsubishi UFJ','INACTIVE'),
('1', '+62', 'DC_VICTORIA_INTERNASIONAL', 'Bank Victoria Internasional','Bank Victoria Internasional','INACTIVE'),
('1', '+62', 'DC_VICTORIA_SYR', 'Bank Victoria Syariah','Bank Victoria Syariah','INACTIVE'),
('1', '+62', 'DC_BANK_SAUDARA', 'Bank Saudara','Bank Saudara','INACTIVE'),
('1', '+62', 'DC_DOKU', 'DOKU','DOKU','INACTIVE'),
('1', '+62', 'DC_SULAWESI_SELATAN_DAN_BARAT', 'Sulawesi Selatan dan Barat','Sulawesi Selatan dan Barat','INACTIVE'),
('1', '+62', 'DC_SULAWESI_UTARA', 'Sulawesi Utara','Sulawesi Utara','INACTIVE'),
('1', '+62', 'DC_SUMATERA_SELATAN', 'Sumatera Selatan','Sumatera Selatan','INACTIVE'),
('1', '+62', 'DC_WOORI_SAUDARA', 'Bank Woori Saudara Indonesia 1906','Bank Woori Saudara Indonesia 1906','INACTIVE'),
('1', '+62', 'DC_ANZ_PANIN_BANK', 'ANZ PANIN BANK','ANZ PANIN BANK','INACTIVE'),
('1', '+62', 'DC_BANK_MAYBANK_INDONESIA', 'BANK MAYBANK INDONESIA','BANK MAYBANK INDONESIA','INACTIVE'),
('1', '+62', 'DC_BANK_OF_AMERICA', 'BANK OF AMERICA','BANK OF AMERICA','INACTIVE'),
('1', '+62', 'DC_BANK_UOB_BUANA_INDONESIA', 'BANK UOB BUANA INDONESIA','BANK UOB BUANA INDONESIA','INACTIVE'),
('1', '+62', 'DC_BPD_SUMATERA_UTARA', 'BPD SUMATERA UTARA','BPD SUMATERA UTARA','INACTIVE'),
('1', '+62', 'DC_BPD_YOGYAKARTA', 'BPD YOGYAKARTA','BPD YOGYAKARTA','INACTIVE'),
('1', '+62', 'DC_THE_BANK_OF_CHINA', 'THE BANK OF CHINA','THE BANK OF CHINA','INACTIVE');




insert into config_mapping_partner(partner_code, mapping_type, inner_code, partner_mapping_code, partner_mapping_name, status) values
	('pandaIndonesia', 'bank', 'DC_BCA', 'ID_0030','BCA','normal'),
	('pandaIndonesia', 'bank', 'DC_BNI', 'ID_0040','BNI','normal'),
	('pandaIndonesia', 'bank', 'DC_BRI', 'ID_0010','BRI','normal'),
	('pandaIndonesia', 'bank', 'DC_CIMB', 'ID_0060','CIMB NIAGA','normal'),
	('pandaIndonesia', 'bank', 'DC_DANAMON', 'ID_0110','DANAMON','normal'),
	('pandaIndonesia', 'bank', 'DC_MANDIR', 'ID_0020','MANDIRI','normal'),
	('pandaIndonesia', 'bank', 'DC_MEGA', 'ID_0190','MEGA','normal'),
	('pandaIndonesia', 'bank', 'DC_PANIN', 'ID_0070','PANIN','normal'),
	('pandaIndonesia', 'bank', 'DC_PERMATA', 'ID_0120','PERMATA','normal'),
	('pandaIndonesia', 'bank', 'DC_BTN', 'ID_0050','BTN','normal'),
	('pandaIndonesia', 'bank', 'DC_UOB', 'ID_0260','UOB','normal'),
	('pandaIndonesia', 'bank', 'DC_BII', 'ID_0100','MAYBANK','normal'),
	('pandaIndonesia', 'bank', 'DC_BTPN ', 'ID_0080','BTPN','normal'),
	('pandaIndonesia', 'bank', 'DC_ARTHA', 'ID_0300','ARTHA','normal'),
	('pandaIndonesia', 'bank', 'DC_BANK_JATIM', 'ID_0290','JATIM','normal'),
	('pandaIndonesia', 'bank', 'DC_BJB', 'ID_0130','BJB','normal'),
	('pandaIndonesia', 'bank', 'DC_BUKOPIN', 'ID_0170','BUKOPIN ','normal'),
	('pandaIndonesia', 'bank', 'DC_DBS', 'ID_0160','DBS','normal'),
	('pandaIndonesia', 'bank', 'DC_HANA', 'ID_0250','HANA','normal'),
	('pandaIndonesia', 'bank', 'DC_HSBC', 'ID_0140','HSBC','normal'),
	('pandaIndonesia', 'bank', 'DC_ICBC', 'ID_0240','ICBC','normal'),
	('pandaIndonesia', 'bank', 'DC_JAWA_TENGAH', 'ID_0200','BPD JATENG','normal'),
	('pandaIndonesia', 'bank', 'DC_MANDIRI_SYR', 'ID_0150','MANDIRI SYARIAH','normal'),
	('pandaIndonesia', 'bank', 'DC_MAYAPADA', 'ID_0180','MAYAPADA','normal'),
	('pandaIndonesia', 'bank', 'DC_MUAMALAT', 'ID_0230','MUAMALAT','normal'),
	('pandaIndonesia', 'bank', 'DC_NUSA_TENGGARA_BARAT', 'ID_0270','NUSA_TENGGARA_BARAT','normal'),
	('pandaIndonesia', 'bank', 'DC_OCBC', 'ID_0090','OCBC NISP','normal'),
	('pandaIndonesia', 'bank', 'DC_SINARMAS', 'ID_0280','SINARMAS','normal'),
	('digitalloan', 'bank', 'DC_BCA', 'BCA','Bank BCA','normal'),
	('digitalloan', 'bank', 'DC_BNI', 'BNI','Bank BNI','normal'),
	('digitalloan', 'bank', 'DC_BRI', 'BRI','BRI','normal'),
	('digitalloan', 'bank', 'DC_CIMB', 'CIMB','Bank CIMB Niaga','normal'),
	('digitalloan', 'bank', 'DC_DANAMON', 'DANAMON','Bank Danamon Indonesia','normal'),
	('digitalloan', 'bank', 'DC_MANDIR', 'MANDIRI','Bank Mandiri','normal'),
	('digitalloan', 'bank', 'DC_MEGA', 'MEGA','Bank Mega','normal'),
	('digitalloan', 'bank', 'DC_PANIN', 'PANIN','Bank Panin','normal'),
	('digitalloan', 'bank', 'DC_PERMATA', 'PERMATA','Bank Permata','normal'),
	('digitalloan', 'bank', 'DC_BTN', 'BTN','Bank Tabungan Negara (Persero)','normal'),
	('digitalloan', 'bank', 'DC_UOB', 'UOB','Bank UOB Indonesia','normal'),
	('xinghe', 'bank', 'DC_BCA', 'BCA','Bank Central Asia (BCA)','normal'),
	('xinghe', 'bank', 'DC_BNI', 'BNI','Bank Negara Indonesia (BNI)','normal'),
	('xinghe', 'bank', 'DC_BRI', 'BRI','Bank Rakyat Indonesia (BRI)','normal'),
	('xinghe', 'bank', 'DC_CIMB', 'CIMB','Bank CIMB Niaga','normal'),
	('xinghe', 'bank', 'DC_DANAMON', 'DANAMON','Bank Danamon','normal'),
	('xinghe', 'bank', 'DC_MANDIR', 'MANDIR','Bank Mandiri','normal'),
	('xinghe', 'bank', 'DC_MEGA', 'MEGA','Bank Mega','normal'),
	('xinghe', 'bank', 'DC_PANIN', 'PANIN','Bank Panin','normal'),
	('xinghe', 'bank', 'DC_PERMATA', 'PERMATA','Bank Permata','normal'),
	('xinghe', 'bank', 'DC_BTN', 'BTN','Bank Tabungan Negara (BTN)','normal'),
	('xinghe', 'bank', 'DC_UOB', 'UOB','Bank UOB Indonesia','normal'),
	('xinghe', 'bank', 'DC_BII', 'BII','Bank Maybank','normal'),
	('xinghe', 'bank', 'DC_ACEH', 'ACEH','BPD Aceh','normal'),
	('xinghe', 'bank', 'DC_ANTAR_DAERAH', 'ANTAR_DAERAH','Bank Antar Daerah','normal'),
	('xinghe', 'bank', 'DC_ARTHA', 'ARTHA','Bank Artha Graha International','normal'),
	('xinghe', 'bank', 'DC_BALI', 'BALI','BPD Bali','normal'),
	('xinghe', 'bank', 'DC_BANK_JATIM', 'BANK JATIM','Bank Jatim','normal'),
	('xinghe', 'bank', 'DC_BCA_SYR', 'BCA_SYR','Bank Central Asia (BCA) Syariah','normal'),
	('xinghe', 'bank', 'DC_BENGKULU', 'BENGKULU','BPD Bengkulu','normal'),
	('xinghe', 'bank', 'DC_BJB', 'BJB','Bank BJB','normal'),
	('xinghe', 'bank', 'DC_BJB_SYR', 'BJB_SYR','Bank BJB Syariah','normal'),
	('xinghe', 'bank', 'DC_BNI_SYR', 'BNI_SYR','Bank BNI Syariah','normal'),
	('xinghe', 'bank', 'DC_BRI_SYR', 'BRI_SYR','Bank Syariah BRI','normal'),
	('xinghe', 'bank', 'DC_BUKOPIN', 'BUKOPIN','Bank Bukopin','normal'),
	('xinghe', 'bank', 'DC_BUKOPIN_SYR', 'BUKOPIN_SYR','Bank Syariah Bukopin','normal'),
	('xinghe', 'bank', 'DC_BUMI_ARTA', 'BUMI_ARTA','Bank Bumi Arta','normal'),
	('xinghe', 'bank', 'DC_CHINATRUST', 'CHINATRUST','Bank Chinatrust Indonesia','normal'),
	('xinghe', 'bank', 'DC_CITIBANK', 'CITIBANK','Citibank','normal'),
	('xinghe', 'bank', 'DC_COMMONWEALTH', 'COMMONWEALTH','Bank Commonwealth','normal'),
	('xinghe', 'bank', 'DC_DBS', 'DBS','Bank DBS Indonesia','normal'),
	('xinghe', 'bank', 'DC_DEUTSCHE', 'DEUTSCHE','Deutsche Bank','normal'),
	('xinghe', 'bank', 'DC_HANA', 'HANA','Bank Hana','normal'),
	('xinghe', 'bank', 'DC_HSBC', 'HSBC','Hongkong and Shanghai Bank Corporation (HSBC)','normal'),
	('xinghe', 'bank', 'DC_ICBC', 'ICBC','Bank ICBC Indonesia','normal'),
	('xinghe', 'bank', 'DC_JAMBI', 'JAMBI','BPD Jambi','normal'),
	('xinghe', 'bank', 'DC_JASA_JAKARTA', 'JASA_JAKARTA','Bank Jasa Jakarta','normal'),
	('xinghe', 'bank', 'DC_JAWA_TENGAH', 'JAWA_TENGAH','BPD Jawa Tengah','normal'),
	('xinghe', 'bank', 'DC_KALIMANTAN_BARAT', 'KALIMANTAN_BARAT','BPD Kalimantan Barat','normal'),
	('xinghe', 'bank', 'DC_KALIMANTAN_SELATAN', 'KALIMANTAN_SELATAN','BPD Kalimantan Selatan','normal'),
	('xinghe', 'bank', 'DC_KALIMANTAN_TENGAH', 'KALIMANTAN_TENGAH','BPD Kalimantan Tengah','normal'),
	('xinghe', 'bank', 'DC_KALIMANTAN_TIMUR', 'KALIMANTAN_TIMUR','BPD Kalimantan Timur','normal'),
	('xinghe', 'bank', 'DC_LAMPUNG', 'LAMPUNG','BPD Lampung','normal'),
	('xinghe', 'bank', 'DC_MALUKU', 'MALUKU','BPD Maluku','normal'),
	('xinghe', 'bank', 'DC_MANDIRI_SYR', 'MANDIRI_SYR','Bank Syariah Mandiri','normal'),
	('xinghe', 'bank', 'DC_MASPION', 'MASPION','Bank Maspion Indonesia','normal'),
	('xinghe', 'bank', 'DC_MAYAPADA', 'MAYAPADA','Bank Mayapada International','normal'),
	('xinghe', 'bank', 'DC_MAYORA', 'MAYORA','Bank Mayora','normal'),
	('xinghe', 'bank', 'DC_MEGA_SYR', 'MEGA_SYR','Bank Syariah Mega','normal'),
	('xinghe', 'bank', 'DC_MITSUI', 'MITSUI','Bank Sumitomo Mitsui Indonesia','normal'),
	('xinghe', 'bank', 'DC_MUAMALAT', 'MUAMALAT','Bank Muamalat Indonesia','normal'),
	('xinghe', 'bank', 'DC_MUTIARA', 'MUTIARA','Bank Mutiara','normal'),
	('xinghe', 'bank', 'DC_NATIONALNOBU', 'NATIONALNOBU','Bank Nationalnobu','normal'),
	('xinghe', 'bank', 'DC_NUSANTARA_PARAHYANGAN', 'NUSANTARA_PARAHYANGAN','Bank Nusantara Parahyangan','normal'),
	('xinghe', 'bank', 'DC_NUSA_TENGGARA_BARAT', 'NUSA_TENGGARA_BARAT','BPD Nusa Tenggara Barat','normal'),
	('xinghe', 'bank', 'DC_NUSA_TENGGARA_TIMUR', 'NUSA_TENGGARA_TIMUR','BPD Nusa Tenggara Timur','normal'),
	('xinghe', 'bank', 'DC_OCBC', 'OCBC','Bank OCBC NISP','normal'),
	('xinghe', 'bank', 'DC_PAPUA', 'PAPUA','BPD Papua','normal'),
	('xinghe', 'bank', 'DC_QNB_KESAWAN', 'QNB_KESAWAN','Bank QNB Kesawan','normal'),
	('xinghe', 'bank', 'DC_RABOBANK', 'RABOBANK','Bank Rabobank International Indonesia','normal'),
	('xinghe', 'bank', 'DC_RBS', 'RBS','Royal Bank of Scotland (RBS)','normal'),
	('xinghe', 'bank', 'DC_RIAU_DAN_KEPRI', 'RIAU_DAN_KEPRI','BPD Riau Dan Kepri','normal'),
	('xinghe', 'bank', 'DC_SAHABAT_SAMPOERNA', 'SAHABAT_SAMPOERNA','Bank Sahabat Sampoerna','normal'),
	('xinghe', 'bank', 'DC_SINARMAS', 'SINARMAS','Sinarmas','normal'),
	('xinghe', 'bank', 'DC_STANDARD_CHARTERED', 'STANDARD_CHARTERED','Standard Charted Bank','normal'),
	('xinghe', 'bank', 'DC_SULAWESI', 'SULAWESI','BPD Sulawesi Tengah','normal'),
	('xinghe', 'bank', 'DC_SULAWESI_TENGGARA', 'SULAWESI_TENGGARA','BPD Sulawesi Tenggara','normal'),
	('xinghe', 'bank', 'DC_SUMATERA_BARAT', 'SUMATERA_BARAT','BPD Sumatera Barat','normal'),
	('xinghe', 'bank', 'DC_TABUNGAN_PENSIUNAN_NASIONAL', 'TABUNGAN_PENSIUNAN_NASIONAL','Bank Tabungan Pensiunan Nasional','normal'),
	('xinghe', 'bank', 'DC_TOKYO', 'TOKYO','Bank of Tokyo Mitsubishi UFJ','normal'),
	('xinghe', 'bank', 'DC_VICTORIA_INTERNASIONAL', 'VICTORIA_INTERNASIONAL','Bank Victoria Internasional','normal'),
	('xinghe', 'bank', 'DC_VICTORIA_SYR', 'VICTORIA_SYR','Bank Victoria Syariah','normal'),
	('xinghe', 'bank', 'DC_BANK_SAUDARA', 'Bank Saudara','Bank Saudara','normal'),
	('xinghe', 'bank', 'DC_DOKU', 'DOKU','DOKU','normal'),
	('xinghe', 'bank', 'DC_SULAWESI_SELATAN_DAN_BARAT', 'Sulawesi Selatan dan Barat','Sulawesi Selatan dan Barat','normal'),
	('xinghe', 'bank', 'DC_SULAWESI_UTARA', 'Sulawesi Utara','Sulawesi Utara','normal'),
	('xinghe', 'bank', 'DC_SUMATERA_SELATAN', 'Sumatera Selatan','Sumatera Selatan','normal'),
	('xinghe', 'bank', 'DC_WOORI_SAUDARA', 'WOORI_SAUDARA','Bank Woori Saudara Indonesia 1906','normal'),
	('xinghe', 'bank', 'DC_ANZ_PANIN_BANK', 'ANZ PANIN BANK','ANZ PANIN BANK','normal'),
	('xinghe', 'bank', 'DC_BANK_MAYBANK_INDONESIA', 'BANK MAYBANK INDONESIA','BANK MAYBANK INDONESIA','normal'),
	('xinghe', 'bank', 'DC_BANK_OF_AMERICA', 'BANK OF AMERICA','BANK OF AMERICA','normal'),
	('xinghe', 'bank', 'DC_BANK_UOB_BUANA_INDONESIA', 'BANK UOB BUANA INDONESIA','BANK UOB BUANA INDONESIA','normal'),
	('xinghe', 'bank', 'DC_BPD_SUMATERA_UTARA', 'BPD SUMATERA UTARA','BPD SUMATERA UTARA','normal'),
	('xinghe', 'bank', 'DC_BPD_YOGYAKARTA', 'BPD YOGYAKARTA','BPD YOGYAKARTA','normal'),
	('xinghe', 'bank', 'DC_THE_BANK_OF_CHINA', 'THE BANK OF CHINA','THE BANK OF CHINA','normal');
